apiVersion: apps/v1
kind: Deployment
metadata: 
  name: users-deployment 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users-deployment
  template:
    metadata:
      labels:
        app: users-deployment
    spec:
      containers:
      - name: users-container 
        image: ghcr.io/muhammadfarrel4148/service-users-ecommerce:latest
        ports:
        - containerPort: 8000

        envFrom: 
        - configMapRef:
            name: users-configmap
        - secretRef:
            name: users-secret

      imagePullSecrets:
      - name: ghcr-creds